### ISSUE TITLE
remindme.sh error

### ISSUE THREAD

**Issue by muralikodali** [chhajedji/scripts#3]
i am using fish shell on Arch Linux.

remindme.sh gave following error.
./remindme.sh: line 41: return: can only `return' from a function or sourced script

**Comment by chhajedji** [comment]
@muralikodali I guess your script is not running with `sh` despite of the shebang `#!/bin/sh` at the start. Nevertheless, I have updated `return` with `exit` in the commit 75e1620c9e44ff6d878b37d4181ce440c433aeed. This should fix the issue.

**Comment by muralikodali** [comment]
Thanks.
there is no error output now.
