### ISSUE TITLE
Any way to make remindme.sh to add periodical reminders?

### ISSUE THREAD

**Issue by thepenguinthatwants** [chhajedji/scripts#6]
Hi Chinmay,
Your script is cool I managed to get it send me on time.
But the feature I would like to have is for a setting to set periodical notifications on every tuesday etc.
Is this doable?

**Comment by chhajedji** [comment]
Hey,

Apologies for the delayed response. This issue slipped out of my mind and only seeing this now. You can use the `cron` command to schedule a notification or any command to run periodically. I would suggest you to look further into this command and use it as per your needs.
